blank_issues_enabled: false
contact_links:
  - name: Comunidade de Suporte
    url: https://github.com/elenderg/Portugues-Puro/discussions
    about: Por favor, faça as perguntas e tire suas dúvidas aqui.

